name: pkdemo
recipe: lamp
config:
  webroot: public
  php: 8.2
  xdebug: true
  config:
    php: .vscode/php.ini
services:
  appserver:
    xdebug: debug
tooling:
  spark:
    service: appserver
    description: Run the CodeIgniter Spark cmd
    cmd:
      - php spark
